apiVersion: v1 # Kubernetes API version 
kind: Pod
metadata:
  name: pod-nginx # pod name
  labels:
    app: nginx_app # label "app=nginx_app" to the pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
